# Put API keys here
keys:
  YandexDictionary: ""
  telegramkey: "1029523944:AAHNhk2lhttzYQg6ptTldv3Y0xGxdIK36so"
  YandexTranslate:
    authorization: "Api-Key AQVNx_gXeDqn7mYexfiz9jYKXQkbcDpitE7GuB92"
    folder_id: "b1gnulfk5aoqhimrv3ff"

# PostgreSQL configuration
database:
  dbname: "memorises"
  initial_dbname: "postgres"
  user: "postgres"
  password: ""
  host: "127.0.0.1"
  port: "5432"
  timeout: 60

# Proxy configuration
# ---
# If you want to use proxy, set
# 'proxy_url' to be the proxy's url,
# e.g. 'socks5://127.0.0.1:1234',
# and optionally uncomment and set
# credentials if required
# ---
proxy:
  proxy_url: ~
  # urllib3_proxy_kwargs:
  #  'username': 'PROXY_USER',
  #  'password': 'PROXY_PASS',

