# Put API keys here
keys:
  YandexDictionary: ""
  telegramkey: ""
  YandexTranslate: ""

# PostgreSQL configuration
database:
  dbname: "memorises"
  initial_dbname: "postgres"
  user: "postgres"
  password: ""
  host: "127.0.0.1"
  port: "5432"
  timeout: 60
